# Maven
# Build your Java projects and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/java

variables:
  configuration: debug
  
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- bash: echo $AGENT_HOMEDIRECTORY $DOWNLOADSECUREFILE_SECUREFILEPATH

- script: ls
  workingDirectory: $(agent.homeDirectory)
  
- task: DownloadSecureFile@1
  inputs:
    secureFile: settings_azure
    
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.10'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    goals: 'deploy -Dautho=$(Build.autho) --settings $DOWNLOADSECUREFILE_SECUREFILEPATH'

