# Maven
# Build your Java projects and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/java

variables:
  configuration: debug
  
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: ls
  workingDirectory: $(agent.homeDirectory)
  
- task: DownloadSecureFile@1
  inputs:
    secureFile: settings_azure
    
- script: ls
  workingDirectory: $(Agent.TempDirectory)

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.10'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    goals: "--settings $(Agent.TempDirectory)/settings_azure deploy"

#- task: PublishBuildArtifacts@1
  #inputs:
    #pathtoPublish: '$(Build.SourcesDirectory)/target/simple-hellow-0.1.0.jar' 
    #artifactName: 'ehayanis.ms-helloworld' 
    #publishLocation: 'Server' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
